load("@rules_idris//idris:rules_idris.bzl", "idris_library")

idris_library (
    name = "library_example4",
    visibility = ["//visibility:public"],
    deps = ["@the_lib5//lib:library_example5"],
)


